### ISSUE TITLE
Is this still underdevelopment?

### ISSUE THREAD

**Issue by Rerum02** [daegalus/beeper-flatpak-wip#1]
Just curious if this is still being worked on, or if the project has been dropped, or hit some roadblock for some reason.

**Comment by daegalus** [comment]
Not fully dropped, but there is a bit of a roadblock/different process.

Beeper said they would take over and make a flatpak and were working with their build service to do it. But I haven't seen anything from them yet.

Another thing is I need to change how this flatpak is built, to comply with Flathub rules about proprietary software in Flatpaks. I just haven't had the time for it.

You can follow the events that happened a bit here: https://github.com/flathub/flathub/pull/4548

I will ping the devs and see what the progress is.

**Comment by jeffgoh** [comment]
Well, now that beeper is part of Auttomatic, they probably have other priorities - seeing as they're opening up the waitlist.  Having said that, any work on getting it into Flathub is going to be appreciated by a lot more people like me who have been on the waitlist forever and who badly need a working option on my Fedora desktop

**Comment by daegalus** [comment]
I got permission from Eric to create the unofficial public Flatpak.

I have been busy with getting ready for a move to a different country, so haven't had time to sit down and get this working. 

I'll probably do it sometime this coming week or the week after.

I'll post here when I have a new PR going on flathub for this.

**Comment by jeffgoh** [comment]
@daegalus looking forward to it. Whilst waiting for the flatpak to arrive, I'm using chat.beeper.com - can't add networks, but otherwise seems usable - just in case anyone else like me doesn't have windows/macos on their desktop/laptop (chromebook works, thankfully)

**Comment by Rerum02** [comment]
Cool to hear, sorry for whatever reason I didn't get a notification of your response. I hope your move went smooth.
